# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  AugmentationCPP_config = debug

else ifeq ($(config),release)
  AugmentationCPP_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := AugmentationCPP

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AugmentationCPP:
ifneq (,$(AugmentationCPP_config))
	@echo "==== Building AugmentationCPP ($(AugmentationCPP_config)) ===="
	@${MAKE} --no-print-directory -C AugmentationCPP -f Makefile config=$(AugmentationCPP_config)
endif

clean:
	@${MAKE} --no-print-directory -C AugmentationCPP -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AugmentationCPP"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"